name: first_app

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.8.0"

flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5
  mongo_dart: ^0.10.8
  http: ^1.6.0
  collection: ^1.17.0
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.0
  build_runner: ^2.11.1
